version: "3"

networks:
	laravel:

services:
	nginx:
		image: nginx:stable-alpine
		container_name: nginx
		ports:
			- "8080:80"
		volumes:
			- ./src:/var/www
			- ./nginx/default.conf:/etc/nginx/conf.d/default.conf
		depends_on:
			- php
			- mysql
		networks:
			-laravel

	laravel:
		build:
			context: .
			dockerFile: Dockerfile
		ports:
			- "8080:80"
		container_name: laravel
		env_file:
			- .env
		volumes:
			- ./src:/var/www
		networks:
			- laravel

	mysql:
		image: mysql:8.0
    	volumes:
      		- ./db/dbdata:/var/lib/mysql
      		- ./db/my.cnf:/etc/mysql/conf.d/my.cnf
   		environment:
			MYSQL_DATABASE: laravel
			MYSQL_USER: root
			MYSQL_PASSWORD:
			MYSQL_ROOT_PASSWORD:
			SERVICE_NAME:	mysql
    	ports:
			- "33061:3306"
		networks:
			- laravel

	volumes:
	mysql: